apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fintrack-application
  namespace: fintrack
spec:
  project: default

  source:
    repoURL: https://github.com/sovanseyha/fintrack-argocd.git
    targetRevision: main
    path: app

  destination: 
    server: https://kubernetes.default.svc
    namespace: fintrack

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
