apiVersion: v1
kind: Service
metadata:
  name: fintrack-service
spec:
  selector:
    app: fintrack
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30010
      targetPort: 8080
